export enum FILING_STATUS_OPTION {
  SINGLE = 'SINGLE',
  MARRIED_FILING_JOINTLY = 'MARRIED_FILING_JOINTLY',
  MARRIED_FILING_SEPARATELY = 'MARRIED_FILING_SEPARATELY',
  HEAD_OF_HOUSEHOLD_W_CHILDREN = 'HEAD_OF_HOUSEHOLD_W_CHILDREN',
}

export enum HEALTH_INSURANCE_OPTION {
  INDEPENDENT_PURCHASE = 'INDEPENDENT_PURCHASE',
  SPOUSE_EMPLOYER = 'SPOUSE_EMPLOYER',
  NOT_COVERED = 'NOT_COVERED',
}

export enum VENDOR_1099_OPTION {
  YES = 'YES',
  DONT_KNOW = 'DONT_KNOW',
  NO = 'NO',
}

export enum RETIREMENT_PROGRAM_OPTION {
  RETIREMENT_PLAN_EXISTS = 'RETIREMENT_PLAN_EXISTS',
  RETIREMENT_PLAN_DESIRED = 'RETIREMENT_PLAN_DESIRED',
  RETIREMENT_PLAN_DECLINED = 'RETIREMENT_PLAN_DECLINED',
}

export enum RETIREMENT_PLAN_LIST {
  SOLO_INDIVIDUAL_401K = 'SOLO_INDIVIDUAL_401K',
  SEP = 'SEP',
  SIMPLE = 'SIMPLE',
  SMALL_EMPLOYER_401K = 'SMALL_EMPLOYER_401K',
  OTHER = 'OTHER',
}

export enum COMPLETION_STATUS {
  NO_INFORMATION = 'NO_INFORMATION',
  INFO_RECEIVED = 'INFORMATION_RECEIVED',
  ESCALATION = 'ESCALATION',
  COMPLETED = 'COMPLETED',
}

export enum TARGET_RETIREMENT_CONTRIBUTION {
  UNDER_5000 = 'UNDER_5000',
  BETWEEN_5000_10000 = 'BETWEEN_5000_10000',
  BETWEEN_10000_20000 = 'BETWEEN_10000_20000',
  BETWEEN_20000_40000 = 'BETWEEN_20000_40000',
  ABOVE_40000 = 'ABOVE_40000',
  OTHER = 'OTHER',
}

export const FilingStatusOptionToLabel = {
  [FILING_STATUS_OPTION.SINGLE]: 'Single',
  [FILING_STATUS_OPTION.MARRIED_FILING_JOINTLY]: 'Married filing jointly',
  [FILING_STATUS_OPTION.MARRIED_FILING_SEPARATELY]: 'Married filing separately',
  [FILING_STATUS_OPTION.HEAD_OF_HOUSEHOLD_W_CHILDREN]: 'Head of Household w/ Children',
};

export const HealthInsuranceOptionToLabel = {
  [HEALTH_INSURANCE_OPTION.INDEPENDENT_PURCHASE]: 'Purchased independently',
  [HEALTH_INSURANCE_OPTION.SPOUSE_EMPLOYER]: 'Through my spouses employer',
  [HEALTH_INSURANCE_OPTION.NOT_COVERED]: 'Not covered for 2021',
};

export const Vendor1099OptionToLabel = {
  [VENDOR_1099_OPTION.YES]: 'Yes',
  [VENDOR_1099_OPTION.DONT_KNOW]: "Don't know. I need help understanding",
  [VENDOR_1099_OPTION.NO]:
    'No, I did not pay any vendor over $600 cash/check/venmo in the calendar year',
};

export const RetirementProgramOptionToLabel = {
  [RETIREMENT_PROGRAM_OPTION.RETIREMENT_PLAN_EXISTS]:
    'Yes, I have a plan set up',
  [RETIREMENT_PROGRAM_OPTION.RETIREMENT_PLAN_DESIRED]:
    'No, but I would like one',
  [RETIREMENT_PROGRAM_OPTION.RETIREMENT_PLAN_DECLINED]:
    'No, not interested this year',
};

export const RetirementPlanListToLabel = {
  [RETIREMENT_PLAN_LIST.SOLO_INDIVIDUAL_401K]: 'Solo/Individual 401k',
  [RETIREMENT_PLAN_LIST.SEP]: 'SEP',
  [RETIREMENT_PLAN_LIST.SIMPLE]: 'SIMPLE',
  [RETIREMENT_PLAN_LIST.SMALL_EMPLOYER_401K]: 'Small employer 401k (with employees more than yourself)',
  [RETIREMENT_PLAN_LIST.OTHER]: 'Other',
};

export const CompletionStatusToLabel = {
  [COMPLETION_STATUS.NO_INFORMATION]: 'No Information',
  [COMPLETION_STATUS.INFO_RECEIVED]: 'Info Received',
  [COMPLETION_STATUS.ESCALATION]: 'Escalation',
  [COMPLETION_STATUS.COMPLETED]: 'Completed',
};

export const TargetRetirementContributionToLabel = {
  [TARGET_RETIREMENT_CONTRIBUTION.UNDER_5000]: '$0 - $5,000',
  [TARGET_RETIREMENT_CONTRIBUTION.BETWEEN_5000_10000]: '$5,000 - $10,000',
  [TARGET_RETIREMENT_CONTRIBUTION.BETWEEN_10000_20000]: '$10,000 - $20,000',
  [TARGET_RETIREMENT_CONTRIBUTION.BETWEEN_20000_40000]: '$20,000 - $40,000',
  [TARGET_RETIREMENT_CONTRIBUTION.ABOVE_40000]: '$40,000',
  [TARGET_RETIREMENT_CONTRIBUTION.OTHER]: 'Other',
};

export const retirementContributionIsOther = (val: string) => {
  if (
    val === TARGET_RETIREMENT_CONTRIBUTION.UNDER_5000
    || val === TARGET_RETIREMENT_CONTRIBUTION.BETWEEN_5000_10000
    || val === TARGET_RETIREMENT_CONTRIBUTION.BETWEEN_10000_20000
    || val === TARGET_RETIREMENT_CONTRIBUTION.BETWEEN_20000_40000
    || val === TARGET_RETIREMENT_CONTRIBUTION.ABOVE_40000
  ) {
    return false;
  }
  return true;
};
