export { Step1 } from './Step1';
export { Step2 } from './Step2';
export { Step3 } from './Step3';
export { Step4 } from './Step4';
export { Step5 } from './Step5';
export { Step6 } from './Step6';
export { Step7 } from './Step7';
export { Step8 } from './Step8';
export { Step9 } from './Step9';
export { Result as ResultDesktop } from 'components/calculator/result/desktop/Result';
export { Result as ResultMobile } from './result/mobile/Result';
